name: explicit_workspace
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - packages/explicit
  - packages/explicit_outcome

dev_dependencies:
  melos: ^7.8.2

melos:
  repository: https://github.com/danxorzum/explicit
  resolution: workspace

  scripts:
    pubget:all:
      description: Run `flutter pub get` in all packages.
      exec: dart pub get
