name: explicit_outcome
resolution: workspace
description: Dart typed outcomes for explicit, predictable development.
version: 0.0.2
license: MPL-2.0
homepage: https://github.com/danxorzum/explicit/tree/main/packages/explicit_outcome
repository: https://github.com/danxorzum/explicit
issue_tracker: https://github.com/danxorzum/explicit/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.5
  test: ">=1.25.0 <2.0.0"
  very_good_analysis: ^7.0.0
dependencies:
  meta: ">=1.15.0 <2.0.0"
