// Mirrors the public command shape generated by Very Good CLI.
// ignore_for_file: public_member_api_docs

import 'package:args/command_runner.dart';
import 'package:explicit_example/src/demo_output.dart';
import 'package:mason_logger/mason_logger.dart';

/// {@template demo_command}
/// A command that prints the explicit Result package walkthrough.
/// {@endtemplate}
class DemoCommand extends Command<int> {
  /// {@macro demo_command}
  DemoCommand({required this._logger});

  static const commandName = 'demo';

  @override
  String get description => 'Print the explicit Result package walkthrough.';

  @override
  String get name => commandName;

  final Logger _logger;

  @override
  Future<int> run() async {
    final output = await buildDemoOutput();
    output.forEach(_logger.info);
    return ExitCode.success.code;
  }
}
