// Mirrors the public surface generated by Very Good CLI.
// ignore_for_file: public_member_api_docs

import 'package:args/args.dart';
import 'package:args/command_runner.dart';
import 'package:cli_completion/cli_completion.dart';
import 'package:explicit_example/src/commands/commands.dart';
import 'package:explicit_example/src/version.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:pub_updater/pub_updater.dart';

const executableName = 'explicit_example';
const packageName = 'explicit_example';
const description =
    'A Very Good Dart CLI example for the explicit Result package.';

/// {@template explicit_example_command_runner}
/// A [CommandRunner] for the CLI.
///
/// ```bash
/// $ explicit_example --version
/// ```
/// {@endtemplate}
class ExplicitExampleCommandRunner extends CompletionCommandRunner<int> {
  /// {@macro explicit_example_command_runner}
  ExplicitExampleCommandRunner({Logger? logger, PubUpdater? pubUpdater})
    : _logger = logger ?? Logger(),
      _pubUpdater = pubUpdater ?? PubUpdater(),
      super(executableName, description) {
    argParser
      ..addFlag(
        'version',
        abbr: 'v',
        negatable: false,
        help: 'Print the current version.',
      )
      ..addFlag(
        'verbose',
        help: 'Noisy logging, including all shell commands executed.',
      );

    addCommand(DemoCommand(logger: _logger));
    addCommand(UpdateCommand(logger: _logger, pubUpdater: _pubUpdater));
  }

  @override
  void printUsage() => _logger.info(usage);

  final Logger _logger;
  final PubUpdater _pubUpdater;

  @override
  Future<int> run(Iterable<String> args) async {
    try {
      final topLevelResults = parse(args);
      if (topLevelResults['verbose'] == true) {
        _logger.level = Level.verbose;
      }
      return await runCommand(topLevelResults) ?? ExitCode.success.code;
    } on FormatException catch (e, stackTrace) {
      _logger
        ..err(e.message)
        ..err('$stackTrace')
        ..info('')
        ..info(usage);
      return ExitCode.usage.code;
    } on UsageException catch (e) {
      _logger
        ..err(e.message)
        ..info('')
        ..info(e.usage);
      return ExitCode.usage.code;
    }
  }

  @override
  Future<int?> runCommand(ArgResults topLevelResults) async {
    if (topLevelResults.command?.name == 'completion') {
      await super.runCommand(topLevelResults);
      return ExitCode.success.code;
    }

    if (topLevelResults['version'] == true) {
      _logger.info(packageVersion);
      return ExitCode.success.code;
    }

    if (topLevelResults.command == null) {
      return DemoCommand(logger: _logger).run();
    }

    final exitCode = await super.runCommand(topLevelResults);

    if (topLevelResults.command?.name != UpdateCommand.commandName) {
      await _checkForUpdates();
    }

    return exitCode;
  }

  Future<void> _checkForUpdates() async {
    try {
      final latestVersion = await _pubUpdater.getLatestVersion(packageName);
      final isUpToDate = packageVersion == latestVersion;
      if (!isUpToDate) {
        _logger
          ..info('')
          ..info('Update available! $packageVersion → $latestVersion')
          ..info('Run $executableName update to update');
      }
    } on Exception catch (_) {
      _logger.err('Failed to check for updates.');
    }
  }
}
