name: explicit_example
description: Example command-line app for the explicit package.
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cli_completion: ^0.5.1
  explicit:
    path: ../

dev_dependencies:
  very_good_analysis: ^7.0.0
